Add SerGo validator info
Cerebellum-Network/staking-dashboard pull request #23
Opened 2023-10-06 14:38 UTC by CrazySerGo

2023-10-09 12:46 UTC, shamilkhan requested changes

2023-10-09 12:46 UTC, shamilkhan commented on src/config/validators/index.ts
>        ],
@CrazySerGo Thanks for your PR! 
Please, add import of your thumbnail 
```ts
import { ReactComponent as SerGo } from './thumbnails/SerGo.svg';
```

2023-10-09 12:46 UTC, shamilkhan commented on src/config/validators/index.ts
> +      cere: [
Please, run `yarn lint` in order to fix prettier issue
```
  Line 40:14:  Replace `⏎········'6SpjH8swCtFwmntQmdikMWyDKgr59q1cLauePYc2iqwwe6Bv',⏎······` with `'6SpjH8swCtFwmntQmdikMWyDKgr59q1cLauePYc2iqwwe6Bv'`  prettier/prettier
  ```

2023-10-10 10:45 UTC, calmrat approved these changes, later dismissed
Identity info looks good.

2023-10-10 10:48 UTC, calmrat commented
@CrazySerGo you'll need to merge conflicts on your branch; try `git pull` to make sure you're working with the latest upstream head; then resolve the merge any conflicts which are (eg) introduced by other community validator's updating this file at the time time.

2023-10-10 11:43 UTC, CrazySerGo commented
@calmrat my PR was created 4 days ago but you decided to merge PR created a day ago that cause issue.
In my view it's a bad idea to modify one file by multiple validators if you don't care about queue.

2023-10-10 14:05 UTC, shamilkhan commented
> @calmrat my PR was created 4 days ago but you decided to merge PR created a day ago that cause issue. In my view it's a bad idea to modify one file by multiple validators if you don't care about queue.

@CrazySerGo  Sorry, for that. 
This pull-request was ready faster I mean in terms of running checks. You still need to pull the latest changes from dev-cere and resolve conflicts and your Pull-Request will be merged.
<img width="627" alt="Screenshot 2023-10-10 at 18 05 41" src="https://github.com/Cerebellum-Network/staking-dashboard/assets/32759781/5888e5ef-91da-4f37-ab2c-bec5f260895e">

2023-10-10 14:33 UTC, CrazySerGo commented
> > @calmrat my PR was created 4 days ago but you decided to merge PR created a day ago that cause issue. In my view it's a bad idea to modify one file by multiple validators if you don't care about queue.
> 
> @CrazySerGo Sorry, for that. This pull-request was ready faster I mean in terms of running checks. You still need to pull the latest changes from dev-cere and resolve conflicts and your Pull-Request will be merged. <img alt="Screenshot 2023-10-10 at 18 05 41" width="627" src="https://user-images.githubusercontent.com/32759781/273940617-5888e5ef-91da-4f37-ab2c-bec5f260895e.png">

Sorry, but I do not understand what you want.
Should I modify my request every time when another person creates a request?
I used updated file base on Xameyz merged request, so used latest version in my view. Where is conflict?
Unfortunately I'm not expert with github and <<<<dev-cere means nothing for me.

2023-10-10 14:51 UTC, shamilkhan commented
> > > @calmrat my PR was created 4 days ago but you decided to merge PR created a day ago that cause issue. In my view it's a bad idea to modify one file by multiple validators if you don't care about queue.
> > 
> > 
> > @CrazySerGo Sorry, for that. This pull-request was ready faster I mean in terms of running checks. You still need to pull the latest changes from dev-cere and resolve conflicts and your Pull-Request will be merged. <img alt="Screenshot 2023-10-10 at 18 05 41" width="627" src="https://user-images.githubusercontent.com/32759781/273940617-5888e5ef-91da-4f37-ab2c-bec5f260895e.png">
> 
> Sorry, but I do not understand what you want. Should I modify my request every time when another person creates a request? I used updated file base on Xameyz merged request, so used latest version in my view. Where is conflict? Unfortunately I'm not expert with github and <<<<dev-cere means nothing for me.

Ok, let me create PR for you and resolve all the conflicts.

2023-10-10 15:10 UTC, shamilkhan commented
@CrazySerGo I've added your changes in this [PR](https://github.com/Cerebellum-Network/staking-dashboard/pull/26). Please confirm that everything is OK.

2023-10-10 18:01 UTC, CrazySerGo commented
> @CrazySerGo I've added your changes in this [PR](https://github.com/Cerebellum-Network/staking-dashboard/pull/26). Please confirm that everything is OK.

Thank you. Data is correct.

2023-10-11 08:46 UTC, shamilkhan commented
@CrazySerGo Thank you! I've merged this [PR](https://github.com/Cerebellum-Network/staking-dashboard/pull/26) so we can close this one.

2023-10-11 08:46 UTC, closed without merging