Adding a new Validator Identity for Xameyz
Cerebellum-Network/staking-dashboard pull request #24
Opened 2023-10-09 07:47 UTC by xamey

Submitted a new validator identity.

2023-10-09 12:52 UTC, shamilkhan requested changes

2023-10-09 12:52 UTC, shamilkhan commented on src/config/validators/index.ts
> +      cere: [
Please, run `yarn lint` in order to fix 
```
[eslint] 
src/config/validators/index.ts
  Line 40:14:  Replace `⏎········'6TYC5go4hQ85NxmGK8c658cmJozxeohKfp6YbDGC5r1HJ6nZ'⏎······` with `'6TYC5go4hQ85NxmGK8c658cmJozxeohKfp6YbDGC5r1HJ6nZ'`  prettier/prettier
  Line 44:4:   Insert `,`                                                                                                                              prettier/prettier
  ```

2023-10-09 12:58 UTC, xamey commented on src/config/validators/index.ts
> +      cere: [
done

2023-10-10 09:27 UTC, shamilkhan approved these changes

2023-10-10 09:32 UTC, calmrat approved these changes
Confirmed. Looks good to me! @shamilkhan

2023-10-10 09:32 UTC, merged